(function () {
    const grades = [1, 2, 3, 4, 5, 6];
    const gradeNames = ["一年级", "二年级", "三年级", "四年级", "五年级", "六年级"];
    const causes = ["未标记", "不会做", "计算粗心", "读题理解", "概念单位"];
    const causeTagsByTopic = {
      addsub: ["计算粗心", "读题理解", "不会做"],
      compare: ["读题理解", "计算粗心", "不会做"],
      muldiv: ["概念单位", "计算粗心", "不会做"],
      remainder: ["概念单位", "读题理解", "不会做"],
      mixed: ["计算粗心", "不会做", "读题理解"],
      twostep: ["不会做", "计算粗心", "读题理解"],
      vertical: ["计算粗心", "不会做", "概念单位"],
      large: ["计算粗心", "不会做", "读题理解"],
      geometry: ["概念单位", "读题理解", "不会做"],
      decimal: ["概念单位", "计算粗心", "不会做"],
      fraction: ["概念单位", "不会做", "读题理解"],
      unit: ["概念单位", "读题理解", "不会做"],
      percent: ["概念单位", "读题理解", "不会做"],
      ratio: ["概念单位", "读题理解", "不会做"],
      statistics: ["读题理解", "不会做", "计算粗心"],
      equation: ["不会做", "概念单位", "计算粗心"],
      word: ["读题理解", "不会做", "概念单位"],
      appendix: ["读题理解", "不会做", "概念单位"]
    };
    const points = [
      { id: "g1-10-add", grade: 1, topic: "addsub", label: "10 以内加减", short: "10以内", helper: "数数、凑数、基础加减" },
      { id: "g1-20-add", grade: 1, topic: "addsub", label: "20 以内加减", short: "20以内", helper: "凑十、拆数、简单应用" },
      { id: "g1-vertical", grade: 1, topic: "vertical", label: "20 以内竖式计算", short: "竖式", helper: "个位对齐、从个位算起、只练加减" },
      { id: "g1-two-step", grade: 1, topic: "twostep", label: "20 以内两步加减", short: "两步加减", helper: "连加连减、先算第一步再算第二步" },
      { id: "g1-compare", grade: 1, topic: "compare", label: "数的比较与补数", short: "比较", helper: "谁多谁少、差多少" },
      { id: "g1-shape", grade: 1, topic: "geometry", label: "图形与位置入门", short: "图形位置", helper: "数图形、左右位置、简单排列" },
      { id: "g1-simple-word", grade: 1, topic: "word", label: "一年级简单应用题", short: "一上应用", helper: "一共、还剩、比多比少" },
      { id: "g1-appendix", grade: 1, topic: "appendix", label: "一年级附加题", short: "附加", helper: "找规律、数感、简单排队问题" },
      { id: "g2-100-add", grade: 2, topic: "addsub", label: "100 以内进退位", short: "100以内", helper: "两位数加减、进位退位" },
      { id: "g2-vertical", grade: 2, topic: "vertical", label: "100 以内竖式计算", short: "竖式", helper: "数位对齐、进位退位、写清过程" },
      { id: "g2-two-step", grade: 2, topic: "twostep", label: "100 以内两步运算", short: "两步运算", helper: "连加连减、加减混合、表内乘除两步" },
      { id: "g2-two-step-muldiv", grade: 2, topic: "twostep", label: "表内两步乘除法", short: "乘除两步", helper: "表内乘除连算、先乘后除、先除后乘" },
      { id: "g2-table", grade: 2, topic: "muldiv", label: "乘法口诀", short: "口诀", helper: "乘法意义、表内除法" },
      { id: "g2-table-div", grade: 2, topic: "muldiv", label: "表内除法", short: "表内除", helper: "平均分、想乘算除" },
      { id: "g2-time-money", grade: 2, topic: "unit", label: "时间与人民币", short: "时间钱币", helper: "元角分、时分、简单经过时间" },
      { id: "g2-simple-word", grade: 2, topic: "word", label: "低年级应用题", short: "应用题", helper: "求一共、还剩、每份" },
      { id: "g2-appendix", grade: 2, topic: "appendix", label: "二年级附加题", short: "附加", helper: "周期规律、简单倍数、平均分思维" },
      { id: "g3-multi-add", grade: 3, topic: "addsub", label: "多位数加减", short: "多位加减", helper: "三四位数计算" },
      { id: "g3-vertical", grade: 3, topic: "vertical", label: "多位数竖式计算", short: "竖式", helper: "三位数加减、乘一位数、除一位数" },
      { id: "g3-mul-div", grade: 3, topic: "muldiv", label: "多位数乘除", short: "乘除", helper: "两位数乘一位数、除法" },
      { id: "g3-two-step", grade: 3, topic: "twostep", label: "两步乘除与加减", short: "两步计算", helper: "乘除后加减、先求中间结果" },
      { id: "g3-remainder", grade: 3, topic: "remainder", label: "有余数除法", short: "余数", helper: "商和余数" },
      { id: "g3-perimeter", grade: 3, topic: "geometry", label: "周长入门", short: "周长", helper: "长方形、正方形周长" },
      { id: "g3-unit", grade: 3, topic: "unit", label: "时间与长度单位", short: "单位入门", helper: "米厘米、时分、千克克" },
      { id: "g3-statistics", grade: 3, topic: "statistics", label: "统计图表入门", short: "统计", helper: "读表格、求最多最少、简单合计" },
      { id: "g3-word-two-step", grade: 3, topic: "word", label: "两步应用题", short: "两步应用", helper: "先求中间量，再回答问题" },
      { id: "g3-appendix", grade: 3, topic: "appendix", label: "三年级附加题", short: "附加", helper: "和差倍、植树雏形、有余数综合" },
      { id: "g4-mixed", grade: 4, topic: "mixed", label: "四则混合运算", short: "混合", helper: "先乘除后加减、括号" },
      { id: "g4-vertical", grade: 4, topic: "vertical", label: "多位乘除竖式", short: "乘除竖式", helper: "多位乘法、除法试商、数位对齐" },
      { id: "g4-two-step", grade: 4, topic: "twostep", label: "两步混合计算", short: "两步混合", helper: "括号、乘除优先、两步竖式" },
      { id: "g4-large", grade: 4, topic: "large", label: "大数计算", short: "大数", helper: "万以内到亿以内" },
      { id: "g4-area", grade: 4, topic: "geometry", label: "面积计算", short: "面积", helper: "长方形、正方形面积" },
      { id: "g4-mul-div", grade: 4, topic: "muldiv", label: "多位乘除专项", short: "多位乘除", helper: "两三位数乘除法" },
      { id: "g4-statistics", grade: 4, topic: "statistics", label: "平均数与统计", short: "平均数", helper: "平均数、总量、数据比较" },
      { id: "g4-word", grade: 4, topic: "word", label: "四年级应用题", short: "四上应用", helper: "行程、购物、倍数关系" },
      { id: "g4-appendix", grade: 4, topic: "appendix", label: "四年级附加题", short: "附加", helper: "植树、和差倍、年龄与盈亏入门" },
      { id: "g5-decimal-add", grade: 5, topic: "decimal", label: "小数加减", short: "小数加减", helper: "小数点对齐、位数补零" },
      { id: "g5-vertical", grade: 5, topic: "vertical", label: "小数竖式计算", short: "小数竖式", helper: "小数点对齐、补 0、按整数方法计算" },
      { id: "g5-decimal", grade: 5, topic: "decimal", label: "小数运算", short: "小数", helper: "小数加减乘除" },
      { id: "g5-two-step", grade: 5, topic: "twostep", label: "小数分数两步计算", short: "两步小分", helper: "小数两步、同分母分数两步" },
      { id: "g5-fraction", grade: 5, topic: "fraction", label: "分数基础", short: "分数", helper: "同分母加减、求一个数的几分之几" },
      { id: "g5-unit", grade: 5, topic: "unit", label: "单位换算", short: "单位", helper: "长度、质量、时间" },
      { id: "g5-percent", grade: 5, topic: "percent", label: "百分数与折扣", short: "百分数", helper: "折扣、百分之几" },
      { id: "g5-equation", grade: 5, topic: "equation", label: "简易方程", short: "方程", helper: "用 x 表示未知数、等式两边同变" },
      { id: "g5-volume", grade: 5, topic: "geometry", label: "长方体与正方体", short: "体积", helper: "体积、表面积、棱长和" },
      { id: "g5-word", grade: 5, topic: "word", label: "五年级综合应用题", short: "五上应用", helper: "小数、分数、百分数语境" },
      { id: "g5-appendix", grade: 5, topic: "appendix", label: "五年级附加题", short: "附加", helper: "鸡兔同笼、行程、工程、平均数" },
      { id: "g6-ratio", grade: 6, topic: "ratio", label: "比和比例", short: "比例", helper: "按比例分配" },
      { id: "g6-vertical", grade: 6, topic: "vertical", label: "综合竖式计算", short: "综合竖式", helper: "小数、百分数和多位数竖式计算" },
      { id: "g6-fraction-percent", grade: 6, topic: "fraction", label: "分数百分数综合", short: "综合", helper: "分数、小数、百分数互通" },
      { id: "g6-two-step", grade: 6, topic: "twostep", label: "分百比两步计算", short: "两步综合", helper: "分数、百分数、比和比例的两步计算" },
      { id: "g6-percent", grade: 6, topic: "percent", label: "百分数应用", short: "百分数应用", helper: "折扣、增长、百分之几" },
      { id: "g6-circle", grade: 6, topic: "geometry", label: "圆的周长与面积", short: "圆", helper: "半径、直径、周长、面积" },
      { id: "g6-scale", grade: 6, topic: "ratio", label: "比例尺应用", short: "比例尺", helper: "图上距离、实际距离、比例尺换算" },
      { id: "g6-complex-word", grade: 6, topic: "word", label: "综合应用题", short: "综合应用", helper: "多步列式、单位与关系" },
      { id: "g6-appendix", grade: 6, topic: "appendix", label: "六年级附加题", short: "附加", helper: "浓度、比例、复杂行程、分数百分数综合" }
    ];
    const pointMap = Object.fromEntries(points.map((point) => [point.id, point]));
    const allOption = { id: "auto", label: "按年级混合 / 自适应" };

    window.MathCampQuestionBank = {
      grades,
      gradeNames,
      causes,
      causeTagsByTopic,
      points,
      pointMap,
      allOption
    };
  })();
